---
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about\
    \     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,\
    \ #swagger](http://swagger.io/irc/).      For this sample, you can use the api\
    \ key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Big Data Aplication"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sergio_c_m@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8080"
basePath: "/v2"
tags:
- name: "Tourists"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "Vuelos"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /Incomingflights/findQuantityByCountryOriginBetweenYears/{countryOrigin}:
    get:
      tags:
      - "Incomingflights"
      summary: "Finds Incomingflights by Country Origin"
      description: "Fin number Of Tourist given a country of origin"
      operationId: "find_quantity_by_country_origin"
      produces:
      - "application/xml"
      - "application/json"
      - "integer"
      parameters:
      - name: "countryOrigin"
        in: "path"
        description: "Status values that need to be considered for filter"
        required: true
        type: "integer"
        format: "int64"
      - name: "StartingYear"
        in: "query"
        description: "Starting Year"
        required: true
        type: "integer"
        format: "int64"
      - name: "FinalYear"
        in: "query"
        description: "Final Year"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
        400:
          description: "Invalid country value"
      x-swagger-router-controller: "swagger_server.controllers.incomingflights_controller"
definitions: {}
