# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body8(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, pais: str=None, numero_turistas: int=None):
        """
        Body8 - a model defined in Swagger

        :param pais: The pais of this Body8.
        :type pais: str
        :param numero_turistas: The numero_turistas of this Body8.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'pais': str,
            'numero_turistas': int
        }

        self.attribute_map = {
            'pais': 'Pais',
            'numero_turistas': 'Numero_Turistas'
        }

        self._pais = pais
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body8':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body8 of this Body8.
        :rtype: Body8
        """
        return deserialize_model(dikt, cls)

    @property
    def pais(self) -> str:
        """
        Gets the pais of this Body8.

        :return: The pais of this Body8.
        :rtype: str
        """
        return self._pais

    @pais.setter
    def pais(self, pais: str):
        """
        Sets the pais of this Body8.

        :param pais: The pais of this Body8.
        :type pais: str
        """

        self._pais = pais

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body8.

        :return: The numero_turistas of this Body8.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body8.

        :param numero_turistas: The numero_turistas of this Body8.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

