# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body7(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, pais: str=None, numero_vuelos: int=None):
        """
        Body7 - a model defined in Swagger

        :param pais: The pais of this Body7.
        :type pais: str
        :param numero_vuelos: The numero_vuelos of this Body7.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'pais': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'pais': 'Pais',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._pais = pais
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body7':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body7 of this Body7.
        :rtype: Body7
        """
        return deserialize_model(dikt, cls)

    @property
    def pais(self) -> str:
        """
        Gets the pais of this Body7.

        :return: The pais of this Body7.
        :rtype: str
        """
        return self._pais

    @pais.setter
    def pais(self, pais: str):
        """
        Sets the pais of this Body7.

        :param pais: The pais of this Body7.
        :type pais: str
        """

        self._pais = pais

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body7.

        :return: The numero_vuelos of this Body7.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body7.

        :param numero_vuelos: The numero_vuelos of this Body7.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

