# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body1(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, numero_vuelos: int=None):
        """
        Body1 - a model defined in Swagger

        :param anio: The anio of this Body1.
        :type anio: int
        :param numero_vuelos: The numero_vuelos of this Body1.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'anio': int,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._anio = anio
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body1 of this Body1.
        :rtype: Body1
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body1.

        :return: The anio of this Body1.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body1.

        :param anio: The anio of this Body1.
        :type anio: int
        """

        self._anio = anio

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body1.

        :return: The numero_vuelos of this Body1.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body1.

        :param numero_vuelos: The numero_vuelos of this Body1.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

