# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body9(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, pais: str=None, numero_vuelos: int=None):
        """
        Body9 - a model defined in Swagger

        :param anio: The anio of this Body9.
        :type anio: int
        :param pais: The pais of this Body9.
        :type pais: str
        :param numero_vuelos: The numero_vuelos of this Body9.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'anio': int,
            'pais': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'pais': 'Pais',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._anio = anio
        self._pais = pais
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body9':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body9 of this Body9.
        :rtype: Body9
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body9.

        :return: The anio of this Body9.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body9.

        :param anio: The anio of this Body9.
        :type anio: int
        """

        self._anio = anio

    @property
    def pais(self) -> str:
        """
        Gets the pais of this Body9.

        :return: The pais of this Body9.
        :rtype: str
        """
        return self._pais

    @pais.setter
    def pais(self, pais: str):
        """
        Sets the pais of this Body9.

        :param pais: The pais of this Body9.
        :type pais: str
        """

        self._pais = pais

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body9.

        :return: The numero_vuelos of this Body9.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body9.

        :param numero_vuelos: The numero_vuelos of this Body9.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

