# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body13(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, mes: str=None, numero_vuelos: int=None):
        """
        Body13 - a model defined in Swagger

        :param anio: The anio of this Body13.
        :type anio: int
        :param mes: The mes of this Body13.
        :type mes: str
        :param numero_vuelos: The numero_vuelos of this Body13.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'anio': int,
            'mes': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'mes': 'Mes',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._anio = anio
        self._mes = mes
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body13':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body13 of this Body13.
        :rtype: Body13
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body13.

        :return: The anio of this Body13.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body13.

        :param anio: The anio of this Body13.
        :type anio: int
        """

        self._anio = anio

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body13.

        :return: The mes of this Body13.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body13.

        :param mes: The mes of this Body13.
        :type mes: str
        """

        self._mes = mes

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body13.

        :return: The numero_vuelos of this Body13.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body13.

        :param numero_vuelos: The numero_vuelos of this Body13.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

