# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body5(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ciudad: str=None, numero_vuelos: int=None):
        """
        Body5 - a model defined in Swagger

        :param ciudad: The ciudad of this Body5.
        :type ciudad: str
        :param numero_vuelos: The numero_vuelos of this Body5.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'ciudad': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'ciudad': 'Ciudad',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._ciudad = ciudad
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body5':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body5 of this Body5.
        :rtype: Body5
        """
        return deserialize_model(dikt, cls)

    @property
    def ciudad(self) -> str:
        """
        Gets the ciudad of this Body5.

        :return: The ciudad of this Body5.
        :rtype: str
        """
        return self._ciudad

    @ciudad.setter
    def ciudad(self, ciudad: str):
        """
        Sets the ciudad of this Body5.

        :param ciudad: The ciudad of this Body5.
        :type ciudad: str
        """

        self._ciudad = ciudad

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body5.

        :return: The numero_vuelos of this Body5.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body5.

        :param numero_vuelos: The numero_vuelos of this Body5.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

