# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body2(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, pais: str=None, cantidad: int=None):
        """
        Body2 - a model defined in Swagger

        :param anio: The anio of this Body2.
        :type anio: int
        :param pais: The pais of this Body2.
        :type pais: str
        :param cantidad: The cantidad of this Body2.
        :type cantidad: int
        """
        self.swagger_types = {
            'anio': int,
            'pais': str,
            'cantidad': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'pais': 'Pais',
            'cantidad': 'Cantidad'
        }

        self._anio = anio
        self._pais = pais
        self._cantidad = cantidad

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_2 of this Body2.
        :rtype: Body2
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body2.

        :return: The anio of this Body2.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body2.

        :param anio: The anio of this Body2.
        :type anio: int
        """

        self._anio = anio

    @property
    def pais(self) -> str:
        """
        Gets the pais of this Body2.

        :return: The pais of this Body2.
        :rtype: str
        """
        return self._pais

    @pais.setter
    def pais(self, pais: str):
        """
        Sets the pais of this Body2.

        :param pais: The pais of this Body2.
        :type pais: str
        """

        self._pais = pais

    @property
    def cantidad(self) -> int:
        """
        Gets the cantidad of this Body2.

        :return: The cantidad of this Body2.
        :rtype: int
        """
        return self._cantidad

    @cantidad.setter
    def cantidad(self, cantidad: int):
        """
        Sets the cantidad of this Body2.

        :param cantidad: The cantidad of this Body2.
        :type cantidad: int
        """

        self._cantidad = cantidad

