# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body6(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ciudad: str=None, numero_turistas: int=None):
        """
        Body6 - a model defined in Swagger

        :param ciudad: The ciudad of this Body6.
        :type ciudad: str
        :param numero_turistas: The numero_turistas of this Body6.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'ciudad': str,
            'numero_turistas': int
        }

        self.attribute_map = {
            'ciudad': 'Ciudad',
            'numero_turistas': 'Numero_Turistas'
        }

        self._ciudad = ciudad
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body6':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body6 of this Body6.
        :rtype: Body6
        """
        return deserialize_model(dikt, cls)

    @property
    def ciudad(self) -> str:
        """
        Gets the ciudad of this Body6.

        :return: The ciudad of this Body6.
        :rtype: str
        """
        return self._ciudad

    @ciudad.setter
    def ciudad(self, ciudad: str):
        """
        Sets the ciudad of this Body6.

        :param ciudad: The ciudad of this Body6.
        :type ciudad: str
        """

        self._ciudad = ciudad

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body6.

        :return: The numero_turistas of this Body6.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body6.

        :param numero_turistas: The numero_turistas of this Body6.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

