# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body7(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, mes: str=None, cantidad: int=None):
        """
        Body7 - a model defined in Swagger

        :param anio: The anio of this Body7.
        :type anio: int
        :param mes: The mes of this Body7.
        :type mes: str
        :param cantidad: The cantidad of this Body7.
        :type cantidad: int
        """
        self.swagger_types = {
            'anio': int,
            'mes': str,
            'cantidad': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'mes': 'Mes',
            'cantidad': 'Cantidad'
        }

        self._anio = anio
        self._mes = mes
        self._cantidad = cantidad

    @classmethod
    def from_dict(cls, dikt) -> 'Body7':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body7 of this Body7.
        :rtype: Body7
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body7.

        :return: The anio of this Body7.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body7.

        :param anio: The anio of this Body7.
        :type anio: int
        """

        self._anio = anio

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body7.

        :return: The mes of this Body7.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body7.

        :param mes: The mes of this Body7.
        :type mes: str
        """

        self._mes = mes

    @property
    def cantidad(self) -> int:
        """
        Gets the cantidad of this Body7.

        :return: The cantidad of this Body7.
        :rtype: int
        """
        return self._cantidad

    @cantidad.setter
    def cantidad(self, cantidad: int):
        """
        Sets the cantidad of this Body7.

        :param cantidad: The cantidad of this Body7.
        :type cantidad: int
        """

        self._cantidad = cantidad

