# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body2(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, numero_turistas: int=None):
        """
        Body2 - a model defined in Swagger

        :param anio: The anio of this Body2.
        :type anio: int
        :param numero_turistas: The numero_turistas of this Body2.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'anio': int,
            'numero_turistas': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'numero_turistas': 'Numero_Turistas'
        }

        self._anio = anio
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body2 of this Body2.
        :rtype: Body2
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body2.

        :return: The anio of this Body2.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body2.

        :param anio: The anio of this Body2.
        :type anio: int
        """

        self._anio = anio

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body2.

        :return: The numero_turistas of this Body2.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body2.

        :param numero_turistas: The numero_turistas of this Body2.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

