# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body10(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, pais: str=None, numero_turistas: int=None):
        """
        Body10 - a model defined in Swagger

        :param anio: The anio of this Body10.
        :type anio: int
        :param pais: The pais of this Body10.
        :type pais: str
        :param numero_turistas: The numero_turistas of this Body10.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'anio': int,
            'pais': str,
            'numero_turistas': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'pais': 'Pais',
            'numero_turistas': 'Numero_Turistas'
        }

        self._anio = anio
        self._pais = pais
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body10':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body10 of this Body10.
        :rtype: Body10
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body10.

        :return: The anio of this Body10.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body10.

        :param anio: The anio of this Body10.
        :type anio: int
        """

        self._anio = anio

    @property
    def pais(self) -> str:
        """
        Gets the pais of this Body10.

        :return: The pais of this Body10.
        :rtype: str
        """
        return self._pais

    @pais.setter
    def pais(self, pais: str):
        """
        Sets the pais of this Body10.

        :param pais: The pais of this Body10.
        :type pais: str
        """

        self._pais = pais

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body10.

        :return: The numero_turistas of this Body10.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body10.

        :param numero_turistas: The numero_turistas of this Body10.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

