# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body14(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, mes: str=None, numero_turistas: int=None):
        """
        Body14 - a model defined in Swagger

        :param anio: The anio of this Body14.
        :type anio: int
        :param mes: The mes of this Body14.
        :type mes: str
        :param numero_turistas: The numero_turistas of this Body14.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'anio': int,
            'mes': str,
            'numero_turistas': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'mes': 'Mes',
            'numero_turistas': 'Numero_Turistas'
        }

        self._anio = anio
        self._mes = mes
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body14':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body14 of this Body14.
        :rtype: Body14
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body14.

        :return: The anio of this Body14.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body14.

        :param anio: The anio of this Body14.
        :type anio: int
        """

        self._anio = anio

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body14.

        :return: The mes of this Body14.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body14.

        :param mes: The mes of this Body14.
        :type mes: str
        """

        self._mes = mes

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body14.

        :return: The numero_turistas of this Body14.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body14.

        :param numero_turistas: The numero_turistas of this Body14.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

