# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body3(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, mes: str=None, numero_vuelos: int=None):
        """
        Body3 - a model defined in Swagger

        :param mes: The mes of this Body3.
        :type mes: str
        :param numero_vuelos: The numero_vuelos of this Body3.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'mes': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'mes': 'Mes',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._mes = mes
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body3':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body3 of this Body3.
        :rtype: Body3
        """
        return deserialize_model(dikt, cls)

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body3.

        :return: The mes of this Body3.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body3.

        :param mes: The mes of this Body3.
        :type mes: str
        """

        self._mes = mes

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body3.

        :return: The numero_vuelos of this Body3.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body3.

        :param numero_vuelos: The numero_vuelos of this Body3.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

