# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body11(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, anio: int=None, ciudad: str=None, numero_vuelos: int=None):
        """
        Body11 - a model defined in Swagger

        :param anio: The anio of this Body11.
        :type anio: int
        :param ciudad: The ciudad of this Body11.
        :type ciudad: str
        :param numero_vuelos: The numero_vuelos of this Body11.
        :type numero_vuelos: int
        """
        self.swagger_types = {
            'anio': int,
            'ciudad': str,
            'numero_vuelos': int
        }

        self.attribute_map = {
            'anio': 'Anio',
            'ciudad': 'Ciudad',
            'numero_vuelos': 'Numero_Vuelos'
        }

        self._anio = anio
        self._ciudad = ciudad
        self._numero_vuelos = numero_vuelos

    @classmethod
    def from_dict(cls, dikt) -> 'Body11':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body11 of this Body11.
        :rtype: Body11
        """
        return deserialize_model(dikt, cls)

    @property
    def anio(self) -> int:
        """
        Gets the anio of this Body11.

        :return: The anio of this Body11.
        :rtype: int
        """
        return self._anio

    @anio.setter
    def anio(self, anio: int):
        """
        Sets the anio of this Body11.

        :param anio: The anio of this Body11.
        :type anio: int
        """

        self._anio = anio

    @property
    def ciudad(self) -> str:
        """
        Gets the ciudad of this Body11.

        :return: The ciudad of this Body11.
        :rtype: str
        """
        return self._ciudad

    @ciudad.setter
    def ciudad(self, ciudad: str):
        """
        Sets the ciudad of this Body11.

        :param ciudad: The ciudad of this Body11.
        :type ciudad: str
        """

        self._ciudad = ciudad

    @property
    def numero_vuelos(self) -> int:
        """
        Gets the numero_vuelos of this Body11.

        :return: The numero_vuelos of this Body11.
        :rtype: int
        """
        return self._numero_vuelos

    @numero_vuelos.setter
    def numero_vuelos(self, numero_vuelos: int):
        """
        Sets the numero_vuelos of this Body11.

        :param numero_vuelos: The numero_vuelos of this Body11.
        :type numero_vuelos: int
        """

        self._numero_vuelos = numero_vuelos

