# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body4(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, mes: str=None, numero_turistas: int=None):
        """
        Body4 - a model defined in Swagger

        :param mes: The mes of this Body4.
        :type mes: str
        :param numero_turistas: The numero_turistas of this Body4.
        :type numero_turistas: int
        """
        self.swagger_types = {
            'mes': str,
            'numero_turistas': int
        }

        self.attribute_map = {
            'mes': 'Mes',
            'numero_turistas': 'Numero_Turistas'
        }

        self._mes = mes
        self._numero_turistas = numero_turistas

    @classmethod
    def from_dict(cls, dikt) -> 'Body4':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body4 of this Body4.
        :rtype: Body4
        """
        return deserialize_model(dikt, cls)

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body4.

        :return: The mes of this Body4.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body4.

        :param mes: The mes of this Body4.
        :type mes: str
        """

        self._mes = mes

    @property
    def numero_turistas(self) -> int:
        """
        Gets the numero_turistas of this Body4.

        :return: The numero_turistas of this Body4.
        :rtype: int
        """
        return self._numero_turistas

    @numero_turistas.setter
    def numero_turistas(self, numero_turistas: int):
        """
        Sets the numero_turistas of this Body4.

        :param numero_turistas: The numero_turistas of this Body4.
        :type numero_turistas: int
        """

        self._numero_turistas = numero_turistas

